/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRawatJalanRouteImport } from './routes/report-rawat-jalan'
import { Route as ReportRawatInapDetailedRouteImport } from './routes/report-rawat-inap-detailed'
import { Route as RawatInapRouteImport } from './routes/rawat-inap'
import { Route as BridgingRouteImport } from './routes/bridging'
import { Route as IndexRouteImport } from './routes/index'

const ReportRawatJalanRoute = ReportRawatJalanRouteImport.update({
  id: '/report-rawat-jalan',
  path: '/report-rawat-jalan',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRawatInapDetailedRoute = ReportRawatInapDetailedRouteImport.update({
  id: '/report-rawat-inap-detailed',
  path: '/report-rawat-inap-detailed',
  getParentRoute: () => rootRouteImport,
} as any)
const RawatInapRoute = RawatInapRouteImport.update({
  id: '/rawat-inap',
  path: '/rawat-inap',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgingRoute = BridgingRouteImport.update({
  id: '/bridging',
  path: '/bridging',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bridging': typeof BridgingRoute
  '/rawat-inap': typeof RawatInapRoute
  '/report-rawat-inap-detailed': typeof ReportRawatInapDetailedRoute
  '/report-rawat-jalan': typeof ReportRawatJalanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bridging': typeof BridgingRoute
  '/rawat-inap': typeof RawatInapRoute
  '/report-rawat-inap-detailed': typeof ReportRawatInapDetailedRoute
  '/report-rawat-jalan': typeof ReportRawatJalanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bridging': typeof BridgingRoute
  '/rawat-inap': typeof RawatInapRoute
  '/report-rawat-inap-detailed': typeof ReportRawatInapDetailedRoute
  '/report-rawat-jalan': typeof ReportRawatJalanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bridging'
    | '/rawat-inap'
    | '/report-rawat-inap-detailed'
    | '/report-rawat-jalan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bridging'
    | '/rawat-inap'
    | '/report-rawat-inap-detailed'
    | '/report-rawat-jalan'
  id:
    | '__root__'
    | '/'
    | '/bridging'
    | '/rawat-inap'
    | '/report-rawat-inap-detailed'
    | '/report-rawat-jalan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BridgingRoute: typeof BridgingRoute
  RawatInapRoute: typeof RawatInapRoute
  ReportRawatInapDetailedRoute: typeof ReportRawatInapDetailedRoute
  ReportRawatJalanRoute: typeof ReportRawatJalanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report-rawat-jalan': {
      id: '/report-rawat-jalan'
      path: '/report-rawat-jalan'
      fullPath: '/report-rawat-jalan'
      preLoaderRoute: typeof ReportRawatJalanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-rawat-inap-detailed': {
      id: '/report-rawat-inap-detailed'
      path: '/report-rawat-inap-detailed'
      fullPath: '/report-rawat-inap-detailed'
      preLoaderRoute: typeof ReportRawatInapDetailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rawat-inap': {
      id: '/rawat-inap'
      path: '/rawat-inap'
      fullPath: '/rawat-inap'
      preLoaderRoute: typeof RawatInapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridging': {
      id: '/bridging'
      path: '/bridging'
      fullPath: '/bridging'
      preLoaderRoute: typeof BridgingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BridgingRoute: BridgingRoute,
  RawatInapRoute: RawatInapRoute,
  ReportRawatInapDetailedRoute: ReportRawatInapDetailedRoute,
  ReportRawatJalanRoute: ReportRawatJalanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
