/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifRouteImport } from './routes/tarif'
import { Route as ReportRawatJalanRouteImport } from './routes/report-rawat-jalan'
import { Route as ReportRawatInapRouteImport } from './routes/report-rawat-inap'
import { Route as RekapRouteImport } from './routes/rekap'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as ObatRouteImport } from './routes/obat'
import { Route as BridgingRouteImport } from './routes/bridging'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TarifRawatJalanRouteImport } from './routes/tarif.rawat-jalan'
import { Route as TarifRawatInapRouteImport } from './routes/tarif.rawat-inap'
import { Route as RekapRawatJalanRouteImport } from './routes/rekap.rawat-jalan'
import { Route as RekapRawatInapRouteImport } from './routes/rekap.rawat-inap'
import { Route as ObatStokRouteImport } from './routes/obat.stok'

const TarifRoute = TarifRouteImport.update({
  id: '/tarif',
  path: '/tarif',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRawatJalanRoute = ReportRawatJalanRouteImport.update({
  id: '/report-rawat-jalan',
  path: '/report-rawat-jalan',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRawatInapRoute = ReportRawatInapRouteImport.update({
  id: '/report-rawat-inap',
  path: '/report-rawat-inap',
  getParentRoute: () => rootRouteImport,
} as any)
const RekapRoute = RekapRouteImport.update({
  id: '/rekap',
  path: '/rekap',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ObatRoute = ObatRouteImport.update({
  id: '/obat',
  path: '/obat',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgingRoute = BridgingRouteImport.update({
  id: '/bridging',
  path: '/bridging',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifRawatJalanRoute = TarifRawatJalanRouteImport.update({
  id: '/rawat-jalan',
  path: '/rawat-jalan',
  getParentRoute: () => TarifRoute,
} as any)
const TarifRawatInapRoute = TarifRawatInapRouteImport.update({
  id: '/rawat-inap',
  path: '/rawat-inap',
  getParentRoute: () => TarifRoute,
} as any)
const RekapRawatJalanRoute = RekapRawatJalanRouteImport.update({
  id: '/rawat-jalan',
  path: '/rawat-jalan',
  getParentRoute: () => RekapRoute,
} as any)
const RekapRawatInapRoute = RekapRawatInapRouteImport.update({
  id: '/rawat-inap',
  path: '/rawat-inap',
  getParentRoute: () => RekapRoute,
} as any)
const ObatStokRoute = ObatStokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => ObatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bridging': typeof BridgingRoute
  '/obat': typeof ObatRouteWithChildren
  '/preview': typeof PreviewRoute
  '/rekap': typeof RekapRouteWithChildren
  '/report-rawat-inap': typeof ReportRawatInapRoute
  '/report-rawat-jalan': typeof ReportRawatJalanRoute
  '/tarif': typeof TarifRouteWithChildren
  '/obat/stok': typeof ObatStokRoute
  '/rekap/rawat-inap': typeof RekapRawatInapRoute
  '/rekap/rawat-jalan': typeof RekapRawatJalanRoute
  '/tarif/rawat-inap': typeof TarifRawatInapRoute
  '/tarif/rawat-jalan': typeof TarifRawatJalanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bridging': typeof BridgingRoute
  '/obat': typeof ObatRouteWithChildren
  '/preview': typeof PreviewRoute
  '/rekap': typeof RekapRouteWithChildren
  '/report-rawat-inap': typeof ReportRawatInapRoute
  '/report-rawat-jalan': typeof ReportRawatJalanRoute
  '/tarif': typeof TarifRouteWithChildren
  '/obat/stok': typeof ObatStokRoute
  '/rekap/rawat-inap': typeof RekapRawatInapRoute
  '/rekap/rawat-jalan': typeof RekapRawatJalanRoute
  '/tarif/rawat-inap': typeof TarifRawatInapRoute
  '/tarif/rawat-jalan': typeof TarifRawatJalanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bridging': typeof BridgingRoute
  '/obat': typeof ObatRouteWithChildren
  '/preview': typeof PreviewRoute
  '/rekap': typeof RekapRouteWithChildren
  '/report-rawat-inap': typeof ReportRawatInapRoute
  '/report-rawat-jalan': typeof ReportRawatJalanRoute
  '/tarif': typeof TarifRouteWithChildren
  '/obat/stok': typeof ObatStokRoute
  '/rekap/rawat-inap': typeof RekapRawatInapRoute
  '/rekap/rawat-jalan': typeof RekapRawatJalanRoute
  '/tarif/rawat-inap': typeof TarifRawatInapRoute
  '/tarif/rawat-jalan': typeof TarifRawatJalanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bridging'
    | '/obat'
    | '/preview'
    | '/rekap'
    | '/report-rawat-inap'
    | '/report-rawat-jalan'
    | '/tarif'
    | '/obat/stok'
    | '/rekap/rawat-inap'
    | '/rekap/rawat-jalan'
    | '/tarif/rawat-inap'
    | '/tarif/rawat-jalan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bridging'
    | '/obat'
    | '/preview'
    | '/rekap'
    | '/report-rawat-inap'
    | '/report-rawat-jalan'
    | '/tarif'
    | '/obat/stok'
    | '/rekap/rawat-inap'
    | '/rekap/rawat-jalan'
    | '/tarif/rawat-inap'
    | '/tarif/rawat-jalan'
  id:
    | '__root__'
    | '/'
    | '/bridging'
    | '/obat'
    | '/preview'
    | '/rekap'
    | '/report-rawat-inap'
    | '/report-rawat-jalan'
    | '/tarif'
    | '/obat/stok'
    | '/rekap/rawat-inap'
    | '/rekap/rawat-jalan'
    | '/tarif/rawat-inap'
    | '/tarif/rawat-jalan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BridgingRoute: typeof BridgingRoute
  ObatRoute: typeof ObatRouteWithChildren
  PreviewRoute: typeof PreviewRoute
  RekapRoute: typeof RekapRouteWithChildren
  ReportRawatInapRoute: typeof ReportRawatInapRoute
  ReportRawatJalanRoute: typeof ReportRawatJalanRoute
  TarifRoute: typeof TarifRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarif': {
      id: '/tarif'
      path: '/tarif'
      fullPath: '/tarif'
      preLoaderRoute: typeof TarifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-rawat-jalan': {
      id: '/report-rawat-jalan'
      path: '/report-rawat-jalan'
      fullPath: '/report-rawat-jalan'
      preLoaderRoute: typeof ReportRawatJalanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-rawat-inap': {
      id: '/report-rawat-inap'
      path: '/report-rawat-inap'
      fullPath: '/report-rawat-inap'
      preLoaderRoute: typeof ReportRawatInapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rekap': {
      id: '/rekap'
      path: '/rekap'
      fullPath: '/rekap'
      preLoaderRoute: typeof RekapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obat': {
      id: '/obat'
      path: '/obat'
      fullPath: '/obat'
      preLoaderRoute: typeof ObatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridging': {
      id: '/bridging'
      path: '/bridging'
      fullPath: '/bridging'
      preLoaderRoute: typeof BridgingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarif/rawat-jalan': {
      id: '/tarif/rawat-jalan'
      path: '/rawat-jalan'
      fullPath: '/tarif/rawat-jalan'
      preLoaderRoute: typeof TarifRawatJalanRouteImport
      parentRoute: typeof TarifRoute
    }
    '/tarif/rawat-inap': {
      id: '/tarif/rawat-inap'
      path: '/rawat-inap'
      fullPath: '/tarif/rawat-inap'
      preLoaderRoute: typeof TarifRawatInapRouteImport
      parentRoute: typeof TarifRoute
    }
    '/rekap/rawat-jalan': {
      id: '/rekap/rawat-jalan'
      path: '/rawat-jalan'
      fullPath: '/rekap/rawat-jalan'
      preLoaderRoute: typeof RekapRawatJalanRouteImport
      parentRoute: typeof RekapRoute
    }
    '/rekap/rawat-inap': {
      id: '/rekap/rawat-inap'
      path: '/rawat-inap'
      fullPath: '/rekap/rawat-inap'
      preLoaderRoute: typeof RekapRawatInapRouteImport
      parentRoute: typeof RekapRoute
    }
    '/obat/stok': {
      id: '/obat/stok'
      path: '/stok'
      fullPath: '/obat/stok'
      preLoaderRoute: typeof ObatStokRouteImport
      parentRoute: typeof ObatRoute
    }
  }
}

interface ObatRouteChildren {
  ObatStokRoute: typeof ObatStokRoute
}

const ObatRouteChildren: ObatRouteChildren = {
  ObatStokRoute: ObatStokRoute,
}

const ObatRouteWithChildren = ObatRoute._addFileChildren(ObatRouteChildren)

interface RekapRouteChildren {
  RekapRawatInapRoute: typeof RekapRawatInapRoute
  RekapRawatJalanRoute: typeof RekapRawatJalanRoute
}

const RekapRouteChildren: RekapRouteChildren = {
  RekapRawatInapRoute: RekapRawatInapRoute,
  RekapRawatJalanRoute: RekapRawatJalanRoute,
}

const RekapRouteWithChildren = RekapRoute._addFileChildren(RekapRouteChildren)

interface TarifRouteChildren {
  TarifRawatInapRoute: typeof TarifRawatInapRoute
  TarifRawatJalanRoute: typeof TarifRawatJalanRoute
}

const TarifRouteChildren: TarifRouteChildren = {
  TarifRawatInapRoute: TarifRawatInapRoute,
  TarifRawatJalanRoute: TarifRawatJalanRoute,
}

const TarifRouteWithChildren = TarifRoute._addFileChildren(TarifRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BridgingRoute: BridgingRoute,
  ObatRoute: ObatRouteWithChildren,
  PreviewRoute: PreviewRoute,
  RekapRoute: RekapRouteWithChildren,
  ReportRawatInapRoute: ReportRawatInapRoute,
  ReportRawatJalanRoute: ReportRawatJalanRoute,
  TarifRoute: TarifRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
