/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifRouteImport } from './routes/tarif'
import { Route as ReportRawatJalanRouteImport } from './routes/report-rawat-jalan'
import { Route as ReportRawatInapRouteImport } from './routes/report-rawat-inap'
import { Route as RekapRouteImport } from './routes/rekap'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as ObatRouteImport } from './routes/obat'
import { Route as KlaimRouteImport } from './routes/klaim'
import { Route as IgdRouteImport } from './routes/igd'
import { Route as BridgingRouteImport } from './routes/bridging'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KlaimIndexRouteImport } from './routes/klaim.index'
import { Route as TarifRawatJalanRouteImport } from './routes/tarif.rawat-jalan'
import { Route as TarifRawatInapRouteImport } from './routes/tarif.rawat-inap'
import { Route as TarifRadiologiRouteImport } from './routes/tarif.radiologi'
import { Route as TarifOperasiRouteImport } from './routes/tarif.operasi'
import { Route as TarifLabRouteImport } from './routes/tarif.lab'
import { Route as RekapRawatJalanRouteImport } from './routes/rekap.rawat-jalan'
import { Route as RekapRawatInapRouteImport } from './routes/rekap.rawat-inap'
import { Route as ObatStokRouteImport } from './routes/obat.stok'
import { Route as ObatKadaluwarsaRouteImport } from './routes/obat.kadaluwarsa'
import { Route as ObatDashboardRouteImport } from './routes/obat.dashboard'
import { Route as KlaimRanapIndexRouteImport } from './routes/klaim.ranap.index'
import { Route as IgdTriaseIndexRouteImport } from './routes/igd.triase.index'
import { Route as KlaimRanapNorawatIndexRouteImport } from './routes/klaim.ranap.$norawat.index'
import { Route as IgdTriaseNorawatIndexRouteImport } from './routes/igd.triase.$norawat.index'
import { Route as IgdTriaseNorawatFormRouteImport } from './routes/igd.triase.$norawat.form'

const TarifRoute = TarifRouteImport.update({
  id: '/tarif',
  path: '/tarif',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRawatJalanRoute = ReportRawatJalanRouteImport.update({
  id: '/report-rawat-jalan',
  path: '/report-rawat-jalan',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRawatInapRoute = ReportRawatInapRouteImport.update({
  id: '/report-rawat-inap',
  path: '/report-rawat-inap',
  getParentRoute: () => rootRouteImport,
} as any)
const RekapRoute = RekapRouteImport.update({
  id: '/rekap',
  path: '/rekap',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ObatRoute = ObatRouteImport.update({
  id: '/obat',
  path: '/obat',
  getParentRoute: () => rootRouteImport,
} as any)
const KlaimRoute = KlaimRouteImport.update({
  id: '/klaim',
  path: '/klaim',
  getParentRoute: () => rootRouteImport,
} as any)
const IgdRoute = IgdRouteImport.update({
  id: '/igd',
  path: '/igd',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgingRoute = BridgingRouteImport.update({
  id: '/bridging',
  path: '/bridging',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KlaimIndexRoute = KlaimIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KlaimRoute,
} as any)
const TarifRawatJalanRoute = TarifRawatJalanRouteImport.update({
  id: '/rawat-jalan',
  path: '/rawat-jalan',
  getParentRoute: () => TarifRoute,
} as any)
const TarifRawatInapRoute = TarifRawatInapRouteImport.update({
  id: '/rawat-inap',
  path: '/rawat-inap',
  getParentRoute: () => TarifRoute,
} as any)
const TarifRadiologiRoute = TarifRadiologiRouteImport.update({
  id: '/radiologi',
  path: '/radiologi',
  getParentRoute: () => TarifRoute,
} as any)
const TarifOperasiRoute = TarifOperasiRouteImport.update({
  id: '/operasi',
  path: '/operasi',
  getParentRoute: () => TarifRoute,
} as any)
const TarifLabRoute = TarifLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => TarifRoute,
} as any)
const RekapRawatJalanRoute = RekapRawatJalanRouteImport.update({
  id: '/rawat-jalan',
  path: '/rawat-jalan',
  getParentRoute: () => RekapRoute,
} as any)
const RekapRawatInapRoute = RekapRawatInapRouteImport.update({
  id: '/rawat-inap',
  path: '/rawat-inap',
  getParentRoute: () => RekapRoute,
} as any)
const ObatStokRoute = ObatStokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => ObatRoute,
} as any)
const ObatKadaluwarsaRoute = ObatKadaluwarsaRouteImport.update({
  id: '/kadaluwarsa',
  path: '/kadaluwarsa',
  getParentRoute: () => ObatRoute,
} as any)
const ObatDashboardRoute = ObatDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ObatRoute,
} as any)
const KlaimRanapIndexRoute = KlaimRanapIndexRouteImport.update({
  id: '/ranap/',
  path: '/ranap/',
  getParentRoute: () => KlaimRoute,
} as any)
const IgdTriaseIndexRoute = IgdTriaseIndexRouteImport.update({
  id: '/triase/',
  path: '/triase/',
  getParentRoute: () => IgdRoute,
} as any)
const KlaimRanapNorawatIndexRoute = KlaimRanapNorawatIndexRouteImport.update({
  id: '/ranap/$norawat/',
  path: '/ranap/$norawat/',
  getParentRoute: () => KlaimRoute,
} as any)
const IgdTriaseNorawatIndexRoute = IgdTriaseNorawatIndexRouteImport.update({
  id: '/triase/$norawat/',
  path: '/triase/$norawat/',
  getParentRoute: () => IgdRoute,
} as any)
const IgdTriaseNorawatFormRoute = IgdTriaseNorawatFormRouteImport.update({
  id: '/triase/$norawat/form',
  path: '/triase/$norawat/form',
  getParentRoute: () => IgdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bridging': typeof BridgingRoute
  '/igd': typeof IgdRouteWithChildren
  '/klaim': typeof KlaimRouteWithChildren
  '/obat': typeof ObatRouteWithChildren
  '/preview': typeof PreviewRoute
  '/rekap': typeof RekapRouteWithChildren
  '/report-rawat-inap': typeof ReportRawatInapRoute
  '/report-rawat-jalan': typeof ReportRawatJalanRoute
  '/tarif': typeof TarifRouteWithChildren
  '/obat/dashboard': typeof ObatDashboardRoute
  '/obat/kadaluwarsa': typeof ObatKadaluwarsaRoute
  '/obat/stok': typeof ObatStokRoute
  '/rekap/rawat-inap': typeof RekapRawatInapRoute
  '/rekap/rawat-jalan': typeof RekapRawatJalanRoute
  '/tarif/lab': typeof TarifLabRoute
  '/tarif/operasi': typeof TarifOperasiRoute
  '/tarif/radiologi': typeof TarifRadiologiRoute
  '/tarif/rawat-inap': typeof TarifRawatInapRoute
  '/tarif/rawat-jalan': typeof TarifRawatJalanRoute
  '/klaim/': typeof KlaimIndexRoute
  '/igd/triase': typeof IgdTriaseIndexRoute
  '/klaim/ranap': typeof KlaimRanapIndexRoute
  '/igd/triase/$norawat/form': typeof IgdTriaseNorawatFormRoute
  '/igd/triase/$norawat': typeof IgdTriaseNorawatIndexRoute
  '/klaim/ranap/$norawat': typeof KlaimRanapNorawatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bridging': typeof BridgingRoute
  '/igd': typeof IgdRouteWithChildren
  '/obat': typeof ObatRouteWithChildren
  '/preview': typeof PreviewRoute
  '/rekap': typeof RekapRouteWithChildren
  '/report-rawat-inap': typeof ReportRawatInapRoute
  '/report-rawat-jalan': typeof ReportRawatJalanRoute
  '/tarif': typeof TarifRouteWithChildren
  '/obat/dashboard': typeof ObatDashboardRoute
  '/obat/kadaluwarsa': typeof ObatKadaluwarsaRoute
  '/obat/stok': typeof ObatStokRoute
  '/rekap/rawat-inap': typeof RekapRawatInapRoute
  '/rekap/rawat-jalan': typeof RekapRawatJalanRoute
  '/tarif/lab': typeof TarifLabRoute
  '/tarif/operasi': typeof TarifOperasiRoute
  '/tarif/radiologi': typeof TarifRadiologiRoute
  '/tarif/rawat-inap': typeof TarifRawatInapRoute
  '/tarif/rawat-jalan': typeof TarifRawatJalanRoute
  '/klaim': typeof KlaimIndexRoute
  '/igd/triase': typeof IgdTriaseIndexRoute
  '/klaim/ranap': typeof KlaimRanapIndexRoute
  '/igd/triase/$norawat/form': typeof IgdTriaseNorawatFormRoute
  '/igd/triase/$norawat': typeof IgdTriaseNorawatIndexRoute
  '/klaim/ranap/$norawat': typeof KlaimRanapNorawatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bridging': typeof BridgingRoute
  '/igd': typeof IgdRouteWithChildren
  '/klaim': typeof KlaimRouteWithChildren
  '/obat': typeof ObatRouteWithChildren
  '/preview': typeof PreviewRoute
  '/rekap': typeof RekapRouteWithChildren
  '/report-rawat-inap': typeof ReportRawatInapRoute
  '/report-rawat-jalan': typeof ReportRawatJalanRoute
  '/tarif': typeof TarifRouteWithChildren
  '/obat/dashboard': typeof ObatDashboardRoute
  '/obat/kadaluwarsa': typeof ObatKadaluwarsaRoute
  '/obat/stok': typeof ObatStokRoute
  '/rekap/rawat-inap': typeof RekapRawatInapRoute
  '/rekap/rawat-jalan': typeof RekapRawatJalanRoute
  '/tarif/lab': typeof TarifLabRoute
  '/tarif/operasi': typeof TarifOperasiRoute
  '/tarif/radiologi': typeof TarifRadiologiRoute
  '/tarif/rawat-inap': typeof TarifRawatInapRoute
  '/tarif/rawat-jalan': typeof TarifRawatJalanRoute
  '/klaim/': typeof KlaimIndexRoute
  '/igd/triase/': typeof IgdTriaseIndexRoute
  '/klaim/ranap/': typeof KlaimRanapIndexRoute
  '/igd/triase/$norawat/form': typeof IgdTriaseNorawatFormRoute
  '/igd/triase/$norawat/': typeof IgdTriaseNorawatIndexRoute
  '/klaim/ranap/$norawat/': typeof KlaimRanapNorawatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bridging'
    | '/igd'
    | '/klaim'
    | '/obat'
    | '/preview'
    | '/rekap'
    | '/report-rawat-inap'
    | '/report-rawat-jalan'
    | '/tarif'
    | '/obat/dashboard'
    | '/obat/kadaluwarsa'
    | '/obat/stok'
    | '/rekap/rawat-inap'
    | '/rekap/rawat-jalan'
    | '/tarif/lab'
    | '/tarif/operasi'
    | '/tarif/radiologi'
    | '/tarif/rawat-inap'
    | '/tarif/rawat-jalan'
    | '/klaim/'
    | '/igd/triase'
    | '/klaim/ranap'
    | '/igd/triase/$norawat/form'
    | '/igd/triase/$norawat'
    | '/klaim/ranap/$norawat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bridging'
    | '/igd'
    | '/obat'
    | '/preview'
    | '/rekap'
    | '/report-rawat-inap'
    | '/report-rawat-jalan'
    | '/tarif'
    | '/obat/dashboard'
    | '/obat/kadaluwarsa'
    | '/obat/stok'
    | '/rekap/rawat-inap'
    | '/rekap/rawat-jalan'
    | '/tarif/lab'
    | '/tarif/operasi'
    | '/tarif/radiologi'
    | '/tarif/rawat-inap'
    | '/tarif/rawat-jalan'
    | '/klaim'
    | '/igd/triase'
    | '/klaim/ranap'
    | '/igd/triase/$norawat/form'
    | '/igd/triase/$norawat'
    | '/klaim/ranap/$norawat'
  id:
    | '__root__'
    | '/'
    | '/bridging'
    | '/igd'
    | '/klaim'
    | '/obat'
    | '/preview'
    | '/rekap'
    | '/report-rawat-inap'
    | '/report-rawat-jalan'
    | '/tarif'
    | '/obat/dashboard'
    | '/obat/kadaluwarsa'
    | '/obat/stok'
    | '/rekap/rawat-inap'
    | '/rekap/rawat-jalan'
    | '/tarif/lab'
    | '/tarif/operasi'
    | '/tarif/radiologi'
    | '/tarif/rawat-inap'
    | '/tarif/rawat-jalan'
    | '/klaim/'
    | '/igd/triase/'
    | '/klaim/ranap/'
    | '/igd/triase/$norawat/form'
    | '/igd/triase/$norawat/'
    | '/klaim/ranap/$norawat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BridgingRoute: typeof BridgingRoute
  IgdRoute: typeof IgdRouteWithChildren
  KlaimRoute: typeof KlaimRouteWithChildren
  ObatRoute: typeof ObatRouteWithChildren
  PreviewRoute: typeof PreviewRoute
  RekapRoute: typeof RekapRouteWithChildren
  ReportRawatInapRoute: typeof ReportRawatInapRoute
  ReportRawatJalanRoute: typeof ReportRawatJalanRoute
  TarifRoute: typeof TarifRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarif': {
      id: '/tarif'
      path: '/tarif'
      fullPath: '/tarif'
      preLoaderRoute: typeof TarifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-rawat-jalan': {
      id: '/report-rawat-jalan'
      path: '/report-rawat-jalan'
      fullPath: '/report-rawat-jalan'
      preLoaderRoute: typeof ReportRawatJalanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-rawat-inap': {
      id: '/report-rawat-inap'
      path: '/report-rawat-inap'
      fullPath: '/report-rawat-inap'
      preLoaderRoute: typeof ReportRawatInapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rekap': {
      id: '/rekap'
      path: '/rekap'
      fullPath: '/rekap'
      preLoaderRoute: typeof RekapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obat': {
      id: '/obat'
      path: '/obat'
      fullPath: '/obat'
      preLoaderRoute: typeof ObatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klaim': {
      id: '/klaim'
      path: '/klaim'
      fullPath: '/klaim'
      preLoaderRoute: typeof KlaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/igd': {
      id: '/igd'
      path: '/igd'
      fullPath: '/igd'
      preLoaderRoute: typeof IgdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridging': {
      id: '/bridging'
      path: '/bridging'
      fullPath: '/bridging'
      preLoaderRoute: typeof BridgingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klaim/': {
      id: '/klaim/'
      path: '/'
      fullPath: '/klaim/'
      preLoaderRoute: typeof KlaimIndexRouteImport
      parentRoute: typeof KlaimRoute
    }
    '/tarif/rawat-jalan': {
      id: '/tarif/rawat-jalan'
      path: '/rawat-jalan'
      fullPath: '/tarif/rawat-jalan'
      preLoaderRoute: typeof TarifRawatJalanRouteImport
      parentRoute: typeof TarifRoute
    }
    '/tarif/rawat-inap': {
      id: '/tarif/rawat-inap'
      path: '/rawat-inap'
      fullPath: '/tarif/rawat-inap'
      preLoaderRoute: typeof TarifRawatInapRouteImport
      parentRoute: typeof TarifRoute
    }
    '/tarif/radiologi': {
      id: '/tarif/radiologi'
      path: '/radiologi'
      fullPath: '/tarif/radiologi'
      preLoaderRoute: typeof TarifRadiologiRouteImport
      parentRoute: typeof TarifRoute
    }
    '/tarif/operasi': {
      id: '/tarif/operasi'
      path: '/operasi'
      fullPath: '/tarif/operasi'
      preLoaderRoute: typeof TarifOperasiRouteImport
      parentRoute: typeof TarifRoute
    }
    '/tarif/lab': {
      id: '/tarif/lab'
      path: '/lab'
      fullPath: '/tarif/lab'
      preLoaderRoute: typeof TarifLabRouteImport
      parentRoute: typeof TarifRoute
    }
    '/rekap/rawat-jalan': {
      id: '/rekap/rawat-jalan'
      path: '/rawat-jalan'
      fullPath: '/rekap/rawat-jalan'
      preLoaderRoute: typeof RekapRawatJalanRouteImport
      parentRoute: typeof RekapRoute
    }
    '/rekap/rawat-inap': {
      id: '/rekap/rawat-inap'
      path: '/rawat-inap'
      fullPath: '/rekap/rawat-inap'
      preLoaderRoute: typeof RekapRawatInapRouteImport
      parentRoute: typeof RekapRoute
    }
    '/obat/stok': {
      id: '/obat/stok'
      path: '/stok'
      fullPath: '/obat/stok'
      preLoaderRoute: typeof ObatStokRouteImport
      parentRoute: typeof ObatRoute
    }
    '/obat/kadaluwarsa': {
      id: '/obat/kadaluwarsa'
      path: '/kadaluwarsa'
      fullPath: '/obat/kadaluwarsa'
      preLoaderRoute: typeof ObatKadaluwarsaRouteImport
      parentRoute: typeof ObatRoute
    }
    '/obat/dashboard': {
      id: '/obat/dashboard'
      path: '/dashboard'
      fullPath: '/obat/dashboard'
      preLoaderRoute: typeof ObatDashboardRouteImport
      parentRoute: typeof ObatRoute
    }
    '/klaim/ranap/': {
      id: '/klaim/ranap/'
      path: '/ranap'
      fullPath: '/klaim/ranap'
      preLoaderRoute: typeof KlaimRanapIndexRouteImport
      parentRoute: typeof KlaimRoute
    }
    '/igd/triase/': {
      id: '/igd/triase/'
      path: '/triase'
      fullPath: '/igd/triase'
      preLoaderRoute: typeof IgdTriaseIndexRouteImport
      parentRoute: typeof IgdRoute
    }
    '/klaim/ranap/$norawat/': {
      id: '/klaim/ranap/$norawat/'
      path: '/ranap/$norawat'
      fullPath: '/klaim/ranap/$norawat'
      preLoaderRoute: typeof KlaimRanapNorawatIndexRouteImport
      parentRoute: typeof KlaimRoute
    }
    '/igd/triase/$norawat/': {
      id: '/igd/triase/$norawat/'
      path: '/triase/$norawat'
      fullPath: '/igd/triase/$norawat'
      preLoaderRoute: typeof IgdTriaseNorawatIndexRouteImport
      parentRoute: typeof IgdRoute
    }
    '/igd/triase/$norawat/form': {
      id: '/igd/triase/$norawat/form'
      path: '/triase/$norawat/form'
      fullPath: '/igd/triase/$norawat/form'
      preLoaderRoute: typeof IgdTriaseNorawatFormRouteImport
      parentRoute: typeof IgdRoute
    }
  }
}

interface IgdRouteChildren {
  IgdTriaseIndexRoute: typeof IgdTriaseIndexRoute
  IgdTriaseNorawatFormRoute: typeof IgdTriaseNorawatFormRoute
  IgdTriaseNorawatIndexRoute: typeof IgdTriaseNorawatIndexRoute
}

const IgdRouteChildren: IgdRouteChildren = {
  IgdTriaseIndexRoute: IgdTriaseIndexRoute,
  IgdTriaseNorawatFormRoute: IgdTriaseNorawatFormRoute,
  IgdTriaseNorawatIndexRoute: IgdTriaseNorawatIndexRoute,
}

const IgdRouteWithChildren = IgdRoute._addFileChildren(IgdRouteChildren)

interface KlaimRouteChildren {
  KlaimIndexRoute: typeof KlaimIndexRoute
  KlaimRanapIndexRoute: typeof KlaimRanapIndexRoute
  KlaimRanapNorawatIndexRoute: typeof KlaimRanapNorawatIndexRoute
}

const KlaimRouteChildren: KlaimRouteChildren = {
  KlaimIndexRoute: KlaimIndexRoute,
  KlaimRanapIndexRoute: KlaimRanapIndexRoute,
  KlaimRanapNorawatIndexRoute: KlaimRanapNorawatIndexRoute,
}

const KlaimRouteWithChildren = KlaimRoute._addFileChildren(KlaimRouteChildren)

interface ObatRouteChildren {
  ObatDashboardRoute: typeof ObatDashboardRoute
  ObatKadaluwarsaRoute: typeof ObatKadaluwarsaRoute
  ObatStokRoute: typeof ObatStokRoute
}

const ObatRouteChildren: ObatRouteChildren = {
  ObatDashboardRoute: ObatDashboardRoute,
  ObatKadaluwarsaRoute: ObatKadaluwarsaRoute,
  ObatStokRoute: ObatStokRoute,
}

const ObatRouteWithChildren = ObatRoute._addFileChildren(ObatRouteChildren)

interface RekapRouteChildren {
  RekapRawatInapRoute: typeof RekapRawatInapRoute
  RekapRawatJalanRoute: typeof RekapRawatJalanRoute
}

const RekapRouteChildren: RekapRouteChildren = {
  RekapRawatInapRoute: RekapRawatInapRoute,
  RekapRawatJalanRoute: RekapRawatJalanRoute,
}

const RekapRouteWithChildren = RekapRoute._addFileChildren(RekapRouteChildren)

interface TarifRouteChildren {
  TarifLabRoute: typeof TarifLabRoute
  TarifOperasiRoute: typeof TarifOperasiRoute
  TarifRadiologiRoute: typeof TarifRadiologiRoute
  TarifRawatInapRoute: typeof TarifRawatInapRoute
  TarifRawatJalanRoute: typeof TarifRawatJalanRoute
}

const TarifRouteChildren: TarifRouteChildren = {
  TarifLabRoute: TarifLabRoute,
  TarifOperasiRoute: TarifOperasiRoute,
  TarifRadiologiRoute: TarifRadiologiRoute,
  TarifRawatInapRoute: TarifRawatInapRoute,
  TarifRawatJalanRoute: TarifRawatJalanRoute,
}

const TarifRouteWithChildren = TarifRoute._addFileChildren(TarifRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BridgingRoute: BridgingRoute,
  IgdRoute: IgdRouteWithChildren,
  KlaimRoute: KlaimRouteWithChildren,
  ObatRoute: ObatRouteWithChildren,
  PreviewRoute: PreviewRoute,
  RekapRoute: RekapRouteWithChildren,
  ReportRawatInapRoute: ReportRawatInapRoute,
  ReportRawatJalanRoute: ReportRawatJalanRoute,
  TarifRoute: TarifRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
