import * as m from "drizzle-orm/mysql-core";

export const billing = m.mysqlTable("billing", {
  noindex: m.int("noindex").primaryKey(),
  no_rawat: m.varchar("no_rawat", { length: 17 }),
  tgl_byr: m.date("tgl_byr"),
  no: m.varchar("no", { length: 50 }),
  nm_perawatan: m.varchar("nm_perawatan", { length: 200 }),
  pemisah: m.char("pemisah", { length: 1 }),
  biaya: m.double("biaya"),
  jumlah: m.double("jumlah"),
  tambahan: m.double("tambahan"),
  totalbiaya: m.double("totalbiaya"),
  status: m.mysqlEnum("status", [
    "Laborat",
    "Radiologi",
    "Operasi",
    "Obat",
    "Ranap Dokter",
    "Ranap Dokter Paramedis",
    "Ranap Paramedis",
    "Ralan Dokter",
    "Ralan Dokter Paramedis",
    "Ralan Paramedis",
    "Tambahan",
    "Potongan",
    "Administrasi",
    "Kamar",
    "-",
    "Registrasi",
    "Harian",
    "Service",
    "TtlObat",
    "TtlRanap Dokter",
    "TtlRanap Paramedis",
    "TtlRalan Dokter",
    "TtlRalan Paramedis",
    "TtlKamar",
    "Dokter",
    "Perawat",
    "TtlTambahan",
    "Retur Obat",
    "TtlRetur Obat",
    "Resep Pulang",
    "TtlResep Pulang",
    "TtlPotongan",
    "TtlLaborat",
    "TtlOperasi",
    "TtlRadiologi",
    "Tagihan",
  ]),
});
