import * as m from "drizzle-orm/mysql-core";

export const bridging_sep_internal = m.mysqlTable("bridging_sep_internal", {
  no_sep: m.varchar("no_sep", { length: 40 }).primaryKey(),
  no_rawat: m.varchar("no_rawat", { length: 17 }),
  tglsep: m.date("tglsep"),
  tglrujukan: m.date("tglrujukan"),
  no_rujukan: m.varchar("no_rujukan", { length: 40 }),
  kdppkrujukan: m.varchar("kdppkrujukan", { length: 12 }),
  nmppkrujukan: m.varchar("nmppkrujukan", { length: 200 }),
  kdppkpelayanan: m.varchar("kdppkpelayanan", { length: 12 }),
  nmppkpelayanan: m.varchar("nmppkpelayanan", { length: 200 }),
  jnspelayanan: m.mysqlEnum("jnspelayanan", ["1", "2"]),
  catatan: m.varchar("catatan", { length: 100 }),
  diagawal: m.varchar("diagawal", { length: 10 }),
  nmdiagnosaawal: m.varchar("nmdiagnosaawal", { length: 400 }),
  kdpolitujuan: m.varchar("kdpolitujuan", { length: 15 }),
  nmpolitujuan: m.varchar("nmpolitujuan", { length: 50 }),
  klsrawat: m.mysqlEnum("klsrawat", ["1", "2", "3"]),
  klsnaik: m.mysqlEnum("klsnaik", ["", "1", "2", "3", "4", "5", "6", "7", "8"]),
  pembiayaan: m.mysqlEnum("pembiayaan", ["", "1", "2", "3"]),
  pjnaikkelas: m.varchar("pjnaikkelas", { length: 100 }),
  lakalantas: m.mysqlEnum("lakalantas", ["0", "1", "2", "3"]),
  user: m.varchar("user", { length: 25 }),
  nomr: m.varchar("nomr", { length: 15 }),
  nama_pasien: m.varchar("nama_pasien", { length: 100 }),
  tanggal_lahir: m.date("tanggal_lahir"),
  peserta: m.varchar("peserta", { length: 100 }),
  jkel: m.mysqlEnum("jkel", ["L", "P"]),
  no_kartu: m.varchar("no_kartu", { length: 25 }),
  tglpulang: m.datetime("tglpulang"),
  asal_rujukan: m.mysqlEnum("asal_rujukan", ["1. Faskes 1", "2. Faskes 2(RS)"]),
  eksekutif: m.mysqlEnum("eksekutif", ["0. Tidak", "1.Ya"]),
  cob: m.mysqlEnum("cob", ["0. Tidak", "1.Ya"]),
  notelep: m.varchar("notelep", { length: 40 }),
  katarak: m.mysqlEnum("katarak", ["0. Tidak", "1.Ya"]),
  tglkkl: m.date("tglkkl"),
  keterangankkl: m.varchar("keterangankkl", { length: 100 }),
  suplesi: m.mysqlEnum("suplesi", ["0. Tidak", "1.Ya"]),
  no_sep_suplesi: m.varchar("no_sep_suplesi", { length: 40 }),
  kdprop: m.varchar("kdprop", { length: 10 }),
  nmprop: m.varchar("nmprop", { length: 50 }),
  kdkab: m.varchar("kdkab", { length: 10 }),
  nmkab: m.varchar("nmkab", { length: 50 }),
  kdkec: m.varchar("kdkec", { length: 10 }),
  nmkec: m.varchar("nmkec", { length: 50 }),
  noskdp: m.varchar("noskdp", { length: 40 }),
  kddpjp: m.varchar("kddpjp", { length: 10 }),
  nmdpjp: m.varchar("nmdpjp", { length: 100 }),
  tujuankunjungan: m.mysqlEnum("tujuankunjungan", ["0", "1", "2"]),
  flagprosedur: m.mysqlEnum("flagprosedur", ["", "0", "1"]),
  penunjang: m.mysqlEnum("penunjang", ["", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]),
  asesmenpelayanan: m.mysqlEnum("asesmenpelayanan", ["", "1", "2", "3", "4", "5"]),
  kddpjpplayanan: m.varchar("kddpjpplayanan", { length: 10 }),
  nmdpjplayanan: m.varchar("nmdpjplayanan", { length: 100 }),
});
