import * as m from "drizzle-orm/mysql-core";

export const operasi = m.mysqlTable("operasi", {
  no_rawat: m.varchar("no_rawat", { length: 17 }).primaryKey(),
  tgl_operasi: m.datetime("tgl_operasi"),
  jenis_anasthesi: m.varchar("jenis_anasthesi", { length: 8 }),
  kategori: m.varchar("kategori", { length: 20 }),
  operator1: m.varchar("operator1", { length: 20 }),
  operator2: m.varchar("operator2", { length: 20 }),
  operator3: m.varchar("operator3", { length: 20 }),
  asisten_operator1: m.varchar("asisten_operator1", { length: 20 }),
  asisten_operator2: m.varchar("asisten_operator2", { length: 20 }),
  asisten_operator3: m.varchar("asisten_operator3", { length: 20 }),
  instrumen: m.varchar("instrumen", { length: 20 }),
  dokter_anak: m.varchar("dokter_anak", { length: 20 }),
  perawaat_resusitas: m.varchar("perawaat_resusitas", { length: 20 }),
  dokter_anestesi: m.varchar("dokter_anestesi", { length: 20 }),
  asisten_anestesi: m.varchar("asisten_anestesi", { length: 20 }),
  asisten_anestesi2: m.varchar("asisten_anestesi2", { length: 20 }),
  bidan: m.varchar("bidan", { length: 20 }),
  bidan2: m.varchar("bidan2", { length: 20 }),
  bidan3: m.varchar("bidan3", { length: 20 }),
  perawat_luar: m.varchar("perawat_luar", { length: 20 }),
  omloop: m.varchar("omloop", { length: 20 }),
  omloop2: m.varchar("omloop2", { length: 20 }),
  omloop3: m.varchar("omloop3", { length: 20 }),
  omloop4: m.varchar("omloop4", { length: 20 }),
  omloop5: m.varchar("omloop5", { length: 20 }),
  dokter_pjanak: m.varchar("dokter_pjanak", { length: 20 }),
  dokter_umum: m.varchar("dokter_umum", { length: 20 }),
  kode_paket: m.varchar("kode_paket", { length: 15 }),
  biayaoperator1: m.double("biayaoperator1"),
  biayaoperator2: m.double("biayaoperator2"),
  biayaoperator3: m.double("biayaoperator3"),
  biayaasisten_operator1: m.double("biayaasisten_operator1"),
  biayaasisten_operator2: m.double("biayaasisten_operator2"),
  biayaasisten_operator3: m.double("biayaasisten_operator3"),
  biayainstrumen: m.double("biayainstrumen"),
  biayadokter_anak: m.double("biayadokter_anak"),
  biayaperawaat_resusitas: m.double("biayaperawaat_resusitas"),
  biayadokter_anestesi: m.double("biayadokter_anestesi"),
  biayaasisten_anestesi: m.double("biayaasisten_anestesi"),
  biayaasisten_anestesi2: m.double("biayaasisten_anestesi2"),
  biayabidan: m.double("biayabidan"),
  biayabidan2: m.double("biayabidan2"),
  biayabidan3: m.double("biayabidan3"),
  biayaperawat_luar: m.double("biayaperawat_luar"),
  biayaalat: m.double("biayaalat"),
  biayasewaok: m.double("biayasewaok"),
  akomodasi: m.double("akomodasi"),
  bagian_rs: m.double("bagian_rs"),
  biaya_omloop: m.double("biaya_omloop"),
  biaya_omloop2: m.double("biaya_omloop2"),
  biaya_omloop3: m.double("biaya_omloop3"),
  biaya_omloop4: m.double("biaya_omloop4"),
  biaya_omloop5: m.double("biaya_omloop5"),
  biayasarpras: m.double("biayasarpras"),
  biaya_dokter_pjanak: m.double("biaya_dokter_pjanak"),
  biaya_dokter_umum: m.double("biaya_dokter_umum"),
  status: m.varchar("status", { length: 20 }),
});
