import * as m from "drizzle-orm/mysql-core";

export const pasien = m.mysqlTable("pasien", {
  no_rkm_medis: m.varchar("no_rkm_medis", { length: 15 }).primaryKey(),
  nm_pasien: m.varchar("nm_pasien", { length: 40 }),
  no_ktp: m.varchar("no_ktp", { length: 20 }),
  jk: m.varchar("jk", { length: 5 }),
  tmp_lahir: m.varchar("tmp_lahir", { length: 15 }),
  tgl_lahir: m.date("tgl_lahir"),
  nm_ibu: m.varchar("nm_ibu", { length: 40 }),
  alamat: m.varchar("alamat", { length: 200 }),
  gol_darah: m.varchar("gol_darah", { length: 5 }),
  pekerjaan: m.varchar("pekerjaan", { length: 60 }),
  stts_nikah: m.varchar("stts_nikah", { length: 20 }),
  agama: m.varchar("agama", { length: 12 }),
  tgl_daftar: m.date("tgl_daftar"),
  no_tlp: m.varchar("no_tlp", { length: 40 }),
  umur: m.varchar("umur", { length: 30 }),
  pnd: m.varchar("pnd", { length: 20 }),
  keluarga: m.varchar("keluarga", { length: 20 }),
  namakeluarga: m.varchar("namakeluarga", { length: 50 }),
  kd_pj: m.char("kd_pj", { length: 3 }),
  no_peserta: m.varchar("no_peserta", { length: 25 }),
  kd_kel: m.int("kd_kel"),
  kd_kec: m.int("kd_kec"),
  kd_kab: m.int("kd_kab"),
  pekerjaanpj: m.varchar("pekerjaanpj", { length: 35 }),
  alamatpj: m.varchar("alamatpj", { length: 100 }),
  kelurahanpj: m.varchar("kelurahanpj", { length: 60 }),
  kecamatanpj: m.varchar("kecamatanpj", { length: 60 }),
  kabupatenpj: m.varchar("kabupatenpj", { length: 60 }),
  perusahaan_pasien: m.varchar("perusahaan_pasien", { length: 8 }),
});
