import * as m from "drizzle-orm/mysql-core";

export const pegawai = m.mysqlTable("pegawai", {
  id: m.int("id").primaryKey(),
  nik: m.varchar("nik", { length: 20 }),
  nama: m.varchar("nama", { length: 50 }),
  jk: m.varchar("jk", { length: 10 }),
  jbtn: m.varchar("jbtn", { length: 25 }),
  jnj_jabatan: m.varchar("jnj_jabatan", { length: 5 }),
  kode_kelompok: m.varchar("kode_kelompok", { length: 3 }),
  kode_resiko: m.varchar("kode_resiko", { length: 3 }),
  kode_emergency: m.varchar("kode_emergency", { length: 3 }),
  departemen: m.char("departemen", { length: 4 }),
  bidang: m.varchar("bidang", { length: 15 }),
  stts_wp: m.char("stts_wp", { length: 5 }),
  stts_kerja: m.char("stts_kerja", { length: 3 }),
  npwp: m.varchar("npwp", { length: 15 }),
  pendidikan: m.varchar("pendidikan", { length: 80 }),
  gapok: m.double("gapok"),
  tmp_lahir: m.varchar("tmp_lahir", { length: 20 }),
  tgl_lahir: m.date("tgl_lahir"),
  alamat: m.varchar("alamat", { length: 60 }),
  kota: m.varchar("kota", { length: 20 }),
  mulai_kerja: m.date("mulai_kerja"),
  ms_kerja: m.varchar("ms_kerja", { length: 10 }),
  indexins: m.char("indexins", { length: 4 }),
  bpd: m.varchar("bpd", { length: 50 }),
  rekening: m.varchar("rekening", { length: 25 }),
  stts_aktif: m.varchar("stts_aktif", { length: 20 }),
  wajibmasuk: m.tinyint("wajibmasuk"),
  pengurang: m.double("pengurang"),
  indek: m.tinyint("indek"),
  mulai_kontrak: m.date("mulai_kontrak"),
  cuti_diambil: m.int("cuti_diambil"),
  dankes: m.double("dankes"),
  photo: m.varchar("photo", { length: 500 }),
  no_ktp: m.varchar("no_ktp", { length: 20 }),
});
